# Generated by Django 3.0.1 on 2020-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/profile_default_photo.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
